services:
  database:
    image: postgres:15
    container_name: f1db
    environment:
      POSTGRES_USER: wolfie
      POSTGRES_PASSWORD: password
      POSTGRES_DB: f1data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - f1-net

  pipeline:
    build: .
    container_name: f1pipeline
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: wolfie
      DB_PASSWORD: password
      DB_NAME: f1data
    networks:
      - f1-net

  api:
    build: .
    container_name: f1api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - database
      - pipeline
    environment:
      DB_HOST: database
      DB_USER: wolfie
      DB_PASSWORD: password
      DB_NAME: f1data
    networks:
      - f1-net

volumes:
  postgres_data:

networks:
  f1-net:
    driver: bridge